on: [push]

name: Python Code Checks

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
            libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
            libharfbuzz-dev libfribidi-dev libxcb1-dev
        pip install poetry
        poetry install
        poetry add flake8
        poetry add PyLint
        poetry show -v
        
    - name: Lint with flake8
      run: |
        POETRY_VENV=$(ls -td /home/runner/.cache/pypoetry/virtualenvs/*/ | head -1)
        source $POETRY_VENV/bin/activate
        flake8 app/

    - name: PyLint
      run: |
        POETRY_VENV=$(ls -td /home/runner/.cache/pypoetry/virtualenvs/*/ | head -1)
        source $POETRY_VENV/bin/activate
        pylint --rcfile ./.pylintrc app/

    - name: PipCheck
      run: |
        POETRY_VENV=$(ls -td /home/runner/.cache/pypoetry/virtualenvs/*/ | head -1)
        source $POETRY_VENV/bin/activate
        pip check