on: [push]

name: Python Code Checks

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-dev
        poetry add flake8
        poetry add safety
        poetry add PyLint
        poetry show -v
        
    - name: Lint with flake8
      run: |
        POETRY_VENV=$(ls -td /home/runner/.cache/pypoetry/virtualenvs/*/ | head -1)
        source $POETRY_VENV/bin/activate
        flake8 app/

    - name: PyLint
      run: |
        POETRY_VENV=$(ls -td /home/runner/.cache/pypoetry/virtualenvs/*/ | head -1)
        source $POETRY_VENV/bin/activate
        pylint --rcfile ./.pylintrc app/

    - name: PipCheck
      run: |
        POETRY_VENV=$(ls -td /home/runner/.cache/pypoetry/virtualenvs/*/ | head -1)
        source $POETRY_VENV/bin/activate
        pip check